/**************************************************************************
Copyright 2026 fnas (based in Jira StopWatch by Carsten Gehling)

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
**************************************************************************/
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Runtime.Versioning;

// General Information about an assembly is controlled through the following 
// set of attributes. Change these attribute values to modify the information
// associated with an assembly.
[assembly: AssemblyTitle("Time.Tracking.Jira")]
[assembly: AssemblyDescription("Time.Tracking.Jira for Seabury Solutions")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("Seabury Solutions")]
[assembly: AssemblyProduct("Time.Tracking.Jira")]
[assembly: AssemblyCopyright("Copyright © 2026 fnas (based in Jira StopWatch by Carsten Gehling)")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]

// La aplicacion es solo para Windows: usa WinForms, WPF, GDI+, DPAPI y P/Invoke a user32.
// Normalmente este atributo lo genera el SDK a partir del target framework, pero aca la
// generacion esta apagada (GenerateAssemblyInfo=false) para conservar este archivo, asi que
// hay que declararlo a mano. Sin el, el analizador de compatibilidad (CA1416) da por sentado
// que el codigo tiene que correr en cualquier plataforma y marca cada llamada a esas APIs.
[assembly: SupportedOSPlatform("windows")]

// Setting ComVisible to false makes the types in this assembly not visible
// to COM components.  If you need to access a type in this assembly from
// COM, set the ComVisible attribute to true on that type.
[assembly: ComVisible(false)]

// The following GUID is for the ID of the typelib if this project is exposed to COM
[assembly: Guid("dffb7978-c4a7-4888-9a6b-46dbda53b3c2")]

// Version information for an assembly consists of the following four values:
//
//      Major Version
//      Minor Version 
//      Build Number
//      Revision
//
// You can specify all the values or you can default the Build and Revision Numbers 
// by using the '*' as shown below:
// [assembly: AssemblyVersion("1.0.*")]
// Version attributes are auto-generated by Build\UpdateAssemblyVersion.ps1 using GitVersion.
// See Properties\AssemblyInfo.Generated.cs (created at build time).

[assembly: InternalsVisibleTo("Time.Tracking.JiraTest")]
[assembly: InternalsVisibleTo("DynamicProxyGenAssembly2")]
